### PR TITLE
Add new configuration option "ui.showcursor" to enable or disable bli…

### PR DESCRIPTION
**Pull request by Sniffleupagus**
…nking cursor by name

When ui.fps is not zero, the default UI adds a blinking cursor next to the pwnagotchi name, as a verification that the display is updating. This proposed change adds a configuration option "ui.showcursor" to allow users to disable the cursor. If ui.showcursor is set to "true" in config.toml, the cursor will show, if set "false" in config, the cursor will not be shown. Default behavior if ui.showcursor is not set is maintained (cursor will show). If ui.fps is set to 0, the cursor will not be shown regardless of the ui.showcursor setting.

(tested on a single pwny with showcursor unset, false, and true, multiple times)

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by Sniffleupagus** [comment]
OK

**Comment by HugoDL** [comment]
I tested it on my pwnagotchi running on a Raspberry Pi 3B+, and it works like a charm.

**Comment by rai68** [comment]
i think 
`if 'showcursor' not in self._config['ui'] or self._config['ui']['showcursor'] == True:` 
should be 
`if self._config['ui'].get('cursor', False) == True:`

'cursor' is probably better than 'showcursor'

**Comment by Sniffleupagus** [comment]
I guess the edit went through. The window disappeared while I was typing in the commit comment, so it got cut short.

**Comment by Sniffleupagus** [comment]
OK.  Updated with proposed changes and added to defaults.toml

**Pull request merged**
